processor:
  ignoreTypes:
  ignoreFields:
    - "status$"
    - "TypeMeta$"

render:
  kubernetesVersion: 1.28
  knownTypes:
    - name: SecretObjectReference
      package: sigs.k8s.io/gateway-api/apis/v1beta1
      link: https://grafana.github.io/grafana-operator/docs/api/#grafanadatasource