apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "grafoo.cloudmonkey.org/v1alpha1",
          "kind": "Grafana",
          "metadata": {
            "labels": {
              "app.kubernetes.io/created-by": "grafoo",
              "app.kubernetes.io/instance": "grafana-sample",
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "grafana",
              "app.kubernetes.io/part-of": "grafoo"
            },
            "name": "grafana-sample"
          },
          "spec": {}
        }
      ]
    capabilities: Basic Install
    createdAt: "2024-06-15T20:39:29Z"
    operators.operatorframework.io/builder: operator-sdk-v1.34.2
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v4
  name: grafoo.v0.1.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Grafana is the Schema for the grafanas API
      displayName: Grafana
      kind: Grafana
      name: grafanas.grafoo.cloudmonkey.org
      version: v1alpha1
  description: grafoo deploys Grafana in OpenShift and manages datasources that connects
    to the in-cluster monitoring and loki logging stack
  displayName: Grafoo
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - namespaces
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - ""
          resources:
          - secrets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - serviceaccounts
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - serviceaccounts/token
          verbs:
          - create
          - get
        - apiGroups:
          - ""
          resources:
          - services
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apps
          resources:
          - deployments
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apps
          resources:
          - deployments/status
          verbs:
          - get
        - apiGroups:
          - config.openshift.io
          resources:
          - ingresses
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - grafana.integreatly.org
          resources:
          - grafanadatasources
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - grafana.integreatly.org
          resources:
          - grafanas
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - grafoo.cloudmonkey.org
          resources:
          - grafanas
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - grafoo.cloudmonkey.org
          resources:
          - grafanas/finalizers
          verbs:
          - update
        - apiGroups:
          - grafoo.cloudmonkey.org
          resources:
          - grafanas/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - loki.grafana.com
          resourceNames:
          - logs
          resources:
          - application
          verbs:
          - get
        - apiGroups:
          - loki.grafana.com
          resourceNames:
          - logs
          resources:
          - audit
          verbs:
          - get
        - apiGroups:
          - loki.grafana.com
          resourceNames:
          - logs
          resources:
          - infrastructure
          verbs:
          - get
        - apiGroups:
          - monitoring.coreos.com
          resourceNames:
          - k8s
          resources:
          - prometheuses/api
          verbs:
          - create
          - get
          - update
        - apiGroups:
          - networking.k8s.io
          resources:
          - ingresses
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - clusterrolebindings
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: grafoo-controller-manager
      deployments:
      - label:
          app.kubernetes.io/component: manager
          app.kubernetes.io/created-by: grafoo
          app.kubernetes.io/instance: controller-manager
          app.kubernetes.io/managed-by: kustomize
          app.kubernetes.io/name: deployment
          app.kubernetes.io/part-of: grafoo
          control-plane: controller-manager
        name: grafoo-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                command:
                - /ko-app/grafoo
                image: quay.io/cldmnky/grafoo:latest
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                ports:
                - containerPort: 9443
                  name: webhook-server
                  protocol: TCP
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
                volumeMounts:
                - mountPath: /tmp/k8s-webhook-server/serving-certs
                  name: cert
                  readOnly: true
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=0
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.15.0
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                  protocol: TCP
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 5m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              securityContext:
                runAsNonRoot: true
              serviceAccountName: grafoo-controller-manager
              terminationGracePeriodSeconds: 10
              volumes:
              - name: cert
                secret:
                  defaultMode: 420
                  secretName: webhook-server-cert
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: grafoo-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - observability
  links:
  - name: Grafoo
    url: https://github.com/cldmnky/grafoo
  maintainers:
  - email: magnus@cloudmonkey.org
    name: Magnus Bengtsson
  maturity: alpha
  provider:
    name: grafoo
  version: 0.1.0
  webhookdefinitions:
  - admissionReviewVersions:
    - v1
    containerPort: 443
    deploymentName: grafoo-controller-manager
    failurePolicy: Fail
    generateName: mgrafana.kb.io
    rules:
    - apiGroups:
      - grafoo.cloudmonkey.org
      apiVersions:
      - v1alpha1
      operations:
      - CREATE
      - UPDATE
      resources:
      - grafanas
    sideEffects: None
    targetPort: 9443
    type: MutatingAdmissionWebhook
    webhookPath: /mutate-grafoo-cloudmonkey-org-v1alpha1-grafana
  - admissionReviewVersions:
    - v1
    containerPort: 443
    deploymentName: grafoo-controller-manager
    failurePolicy: Fail
    generateName: vgrafana.kb.io
    rules:
    - apiGroups:
      - grafoo.cloudmonkey.org
      apiVersions:
      - v1alpha1
      operations:
      - CREATE
      - UPDATE
      resources:
      - grafanas
    sideEffects: None
    targetPort: 9443
    type: ValidatingAdmissionWebhook
    webhookPath: /validate-grafoo-cloudmonkey-org-v1alpha1-grafana
