# permissions for end users to view grafanas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: grafana-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: grafoo
    app.kubernetes.io/part-of: grafoo
    app.kubernetes.io/managed-by: kustomize
  name: grafana-viewer-role
rules:
- apiGroups:
  - grafoo.cloudmonkey.org
  resources:
  - grafanas
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - grafoo.cloudmonkey.org
  resources:
  - grafanas/status
  verbs:
  - get
